pipeline{
    agent any
    stages{
        stage ('Build Application'){
            steps{
                sh 'mcn clean package'
            }
            post{
                success{
                    echo "Now Archiving the Artivacts...."
                    archiveArtifacts artifacts: '**/*.jar'
                }
            }
        }
    }
}