pipeline{
    agent any
    stages{
        stage ('Build Application'){
            steps{
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post{
                success{
                    echo "Now Archiving the Artivacts...."
                    archiveArtifacts artifacts: '**/*.jar'
                }
            }
        }
        stage('Deploy in staging enviroment'){
             build job: 'Deploy_app'
             }
    }


}